#!/bin/bash

if test -z "${EPREFIX}"; then
    echo "lims2 environment setup should be run inside Gentoo prefix" >&2
    exit 1
fi

if ! test -d packages; then
    echo "lims2 environment setup should be run in the directory containing the lims2 packages" >&2
    exit 1
fi

export PGHOST="pgsrv5"
export PGPORT=5437
export PGDATABASE=lims2_devel

for LIBDIR in $(pwd)/packages/*/lib $(pwd)/../Eng-Seq-Builder/lib; do
    if test -d "${LIBDIR}"; then
        if test -z "$PERL5LIB"; then
            PERL5LIB="${LIBDIR}"
        else
            PERL5LIB="${LIBDIR}:${PERL5LIB}"
        fi
    fi
done

export PERL5LIB

for BINDIR in $(pwd)/packages/*/bin $(pwd)/packages/*/script; do
    if test -d "${BINDIR}"; then
        if test -z "${PATH}"; then
            PATH="${BINDIR}"
        else
            PATH="${BINDIR}:${PATH}"
        fi
    fi
done

export PATH

export LIMS2_DBCONNECT_CONFIG="$(pwd)/conf/dbconnect.yaml"
export LIMS2_DB="LIMS2_DEVEL"
export ENG_SEQ_BUILDER_CONFIG="$(pwd)/../htgt-conf/eng-seq-builder.yaml"
